//! TIPOS DE IDENTIFICATIVOS PARA LA CEDULA
const TIPO_IDENTIFICAION = ["V","AP"];

//!TIPOS DE STATUS
const DISPONIBILIDAD = [0,1,2,3,4];


//! URL DE CONEXION CON EL BACKEND
const URL_BACKEND = "http://localhost:2488/";


//! TIPOS DE USUARIOS DEL SISTEMA
const TIPO_USUARIO ={
  GESTOR: 3,
  MODULO: 2,
  COORDINACION: 1
};

//! TIPOS DE ESTATU DEL GESTOR
const GESTOR_STATUS ={
	APAGADA: 0,
	CLASES: 1,
	RESERVACION:2,
};


//SIGNIFICADO DE CAD NUMERO DE ESTATUTO 
//! ["DISPONIBLE", "OCUPADO", "EN ESPERA", "ADVERTENCIA-1","ADVERTENCIA-2","TESISTA", "CLASES", "APAGADO", "FUERA DE SERVICIO"];
const CLIENTE_STATUS = {
  DISPONIBLE: 0,
  OCUPADO: 1,
  ESPERA: 2,
  ADVERTENCIA_1: 3,
  ADVERTENCIA_2:4,
  TESISTA:5,
  CLASES:6,
  APAGADO:7,
  EXTENCION:8,
}
export {
    TIPO_IDENTIFICAION,
     DISPONIBILIDAD,
      URL_BACKEND,
      TIPO_USUARIO,
      CLIENTE_STATUS,
      GESTOR_STATUS,
    }